<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>e5e71bbe-5d54-4ab2-a5aa-14f9365fcef3</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Blazor-ApexCharts" Version="7.0.0" />
    <PackageReference Include="Blazored.Typeahead" Version="4.7.0" />
    <PackageReference Include="BlazorTableExtended" Version="1.1.0" />
    <PackageReference Include="bootstrap" Version="5.3.8" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="10.0.12" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.12" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="10.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.12">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    
    
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Components\BatailleEmpire\" />
    <Folder Include="Models\BatailleEmpire\" />
  </ItemGroup>

</Project>
